---
version: 2
multicolumn: 
web-width: 800
export-width: 
align: 
float: 
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/william-playfair-excel-exports/citibike_HW.ipynb
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/174916/articles/210994/master/folder/figures/william-playfair-excel-exports"
    url: "/users/174916/articles/210994/master/file/figures/william-playfair-excel-exports/citibike_HW.ipynb"
