---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/log_distribution/normalized_distribution.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/174916/articles/210994/master/folder/figures/log_distribution"
    url: "/users/174916/articles/210994/master/file/figures/log_distribution/normalized_distribution.png"
